language: php
php:
  - 7.0
  - 7.1
  - nightly
services:
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer self-update
  - composer install --dev
  - composer setup
script:
  - composer test
