language: php
php:
  - 7.0
  - 7.1
  - nightly
services:
  - mysql
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  # Setup display for Selenium
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
  - unzip -o -q chromedriver_linux64.zip

  # Get and run Selenium
  - wget http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.0.jar -O selenium-server-standalone.jar
  - java -Dwebdriver.chrome.driver=`pwd`/chromedriver -jar selenium-server-standalone.jar > /dev/null 2>&1 &

  # Change MySQL root password
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

  # Setup Behat base_url
  - "export BEHAT_PARAMS='{\"extensions\" : {\"Behat\\\\MinkExtension\" : {\"base_url\" : \"'$HTTP_SERVER'\"}}}'"

  # start build-in server
  - composer install
  - composer setup
  - (php -S localhost:8080 -t www &) 2> /dev/null > /dev/null
script:
  - composer behat
  - composer setup
  - composer test
  - composer phpcs
