language: php
php:
  - 7.0
  - 7.1
  - nightly
services:
  - mysql
before_script:
  - composer self-update
  - composer install --dev
  - composer setup
script:
  - composer test
after_success:
  - php vendor/bin/coveralls --verbose
