language: php
php:
  - 7.0
  - 7.1
  - nightly
services:
  - mysql
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  # Setup display for Selenium
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  # Start Chrome headless
  - google-chrome-stable --no-sandbox --no-first-run --disable-extensions --disable-gpu --headless --remote-debugging-port=9222 about:blank &>/dev/null &

  # Change MySQL root password
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

  # Run composer install
  - composer install

  # Setup Behat base_url
  - "export BEHAT_PARAMS='{\"extensions\" : {\"Behat\\\\MinkExtension\" : {\"base_url\" : \"'$HTTP_SERVER'\"}}}'"

  # start build-in server
  - composer setup
  - (php -S localhost:8080 -t www &) 2> /dev/null > /dev/null
  - sleep 2
script:
  - composer behat
  - composer setup
  - composer test
  - composer phpcs
