language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
before_script:
  - composer self-update
  - composer install --dev
  - composer setup
script:
  - composer test
after_success:
  - php vendor/bin/coveralls --verbose
