language: php
php:
  - 7.0
  - 7.1
services:
  - mysql
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  # Change MySQL root password
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

  # Run composer install
  - composer install

  # Setup Behat base_url
  - "export BEHAT_PARAMS='{\"extensions\" : {\"Behat\\\\MinkExtension\" : {\"base_url\" : \"'$HTTP_SERVER'\"}}}'"

  # start build-in server
  - composer setup
  - (php -S localhost:8080 -t www &) 2> /dev/null > /dev/null
  - sleep 2
script:
  - composer test
  - composer setup
  - composer behat
  - composer phpcs
